version: "3.2"
services:
  documentation-web:
    build: .
    mem_limit: ${DOCUMENTATION_WEB_MEM_LIMIT:-5g}
    memswap_limit: ${DOCUMENTATION_WEB_MEMSWAP_LIMITi:-5g}
    cpus: ${DOCUMENTATION_WEB_CPU_LIMIT:-5}
    hostname: documentation-web
    container_name: documentation-web
    restart: unless-stopped
    ports:
      - 38080:80
    volumes:
      - ./volumes/documentation-web/var_www_html/:/usr/local/apache2/htdocs/
        # choose between var_www_html_index-prod.htm, var_www_html_index-test.htm and var_www_html_index-prod.htm with env variable in .env_dist (by default it's "dev")
      - ./volumes/documentation-web/var_www_html_index-${DOCUMENTATION_ENV:-dev}.html:/usr/local/apache2/htdocs/index.html
      - ./volumes/documentation-web/conf/abes/:/usr/local/apache2/conf/abes/
  documentation-gm-swish-e:
    image: abesesr/swish-e-docker:1.1.1
    mem_limit: ${DOCUMENTATION_GM_SWISHE_MEM_LIMIT:-5g}
    memswap_limit: ${DOCUMENTATION_GM_SWISHE_MEMSWAP_LIMITi:-5g}
    cpus: ${DOCUMENTATION_GM_SWISHE_CPU_LIMIT:-5}
    hostname: documentation-gm-swish-e
    container_name: documentation-gm-swish-e
    restart: unless-stopped
    ports:
      - 38081:80
    volumes:
      - ./volumes/documentation-web/var_www_html/guide/html/:/var/www/html/
      - ./volumes/documentation-gm-swish-e/conf-swish-e/swish.cgi:/usr/lib/cgi-bin/swish.cgi
      - ./volumes/documentation-gm-swish-e/conf-swish-e/TemplateDefault.pm:/usr/lib/swish-e/perl/SWISH/TemplateDefault.pm
        # choose between .swishcgi-prod.conf, .swishcgi-test.conf and .swishcgi-prod.conf with env variable in .env_dist (by default it's "dev")
      - ./volumes/documentation-gm-swish-e/conf-swish-e/.swishcgi-${DOCUMENTATION_ENV:-dev}.conf:/usr/lib/cgi-bin/.swishcgi.conf
      - ./volumes/documentation-gm-swish-e/index-swish-e/:/opt/guide/data-swish-e/
      - ./volumes/documentation-gm-swish-e/scripts-swish-e/:/opt/guide/data-swish-e/scripts/
