services:
  documentation-web:
    build: ./images/documentation-web/
    mem_limit: ${DOCUMENTATION_WEB_MEM_LIMIT:-5g}
    cpus: ${DOCUMENTATION_WEB_CPU_LIMIT:-5}
    hostname: documentation-web
    container_name: documentation-web
    restart: unless-stopped
    ports:
      - 38080:80
    environment:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    volumes:
      - ./volumes/documentation-web/var_www_html/:/usr/local/apache2/htdocs/
        # choose between var_www_html_index-dev.htm, var_www_html_index-test.htm and var_www_html_index-prod.htm with env variable in .env_dist (by default it's "dev")
      - ./configs/documentation-web/var_www_html_index-${DOCUMENTATION_ENV:-dev}.html:/usr/local/apache2/htdocs/index.html
      - ./configs/documentation-web/abes_apache_conf/:/usr/local/apache2/conf/abes/
  documentation-gm-swish-e:
    build: ./images/documentation-gm-swish-e/
    mem_limit: ${DOCUMENTATION_GM_SWISHE_MEM_LIMIT:-5g}
    cpus: ${DOCUMENTATION_GM_SWISHE_CPU_LIMIT:-5}
    hostname: documentation-gm-swish-e
    container_name: documentation-gm-swish-e
    restart: unless-stopped
    ports:
      - 38081:80
    volumes:
      - ./volumes/documentation-web/var_www_html/guide/html/:/var/www/html/
      - ./configs/documentation-gm-swish-e/conf-swish-e/swish.cgi:/usr/lib/cgi-bin/swish.cgi
      - ./configs/documentation-gm-swish-e/conf-swish-e/TemplateDefault.pm:/usr/lib/swish-e/perl/SWISH/TemplateDefault.pm
        # choose between .swishcgi-dev.conf, .swishcgi-test.conf and .swishcgi-prod.conf with env variable in .env_dist (by default it's "dev")
      - ./configs/documentation-gm-swish-e/conf-swish-e/.swishcgi-${DOCUMENTATION_ENV:-dev}.conf:/usr/lib/cgi-bin/.swishcgi.conf
      - ./configs/documentation-gm-swish-e/index-swish-e/swishCatalogage.conf:/opt/guide/data-swish-e/swishCatalogage.conf
      - ./configs/documentation-gm-swish-e/index-swish-e/swishPourManuels.conf:/opt/guide/data-swish-e/swishPourManuels.conf
      - ./configs/documentation-gm-swish-e/index-swish-e/swishTout.conf:/opt/guide/data-swish-e/swishTout.conf
      - ./configs/documentation-gm-swish-e/scripts-swish-e/:/opt/guide/data-swish-e/scripts/
  documentation-webdav:
    image: bytemark/webdav:2.4
    mem_limit: ${DOCUMENTATION_WEBDAV_MEM_LIMIT:-5g}
    cpus: ${DOCUMENTATION_WEBDAV_CPU_LIMIT:-5}
    hostname: documentation-webdav
    container_name: documentation-webdav
    restart: unless-stopped
    ports:
      - "38082:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: ${DOCUMENTATION_WEBDAV_USERNAME}
      PASSWORD: ${DOCUMENTATION_WEBDAV_PASSWORD}
      LOCATION: ${DOCUMENTATION_WEBDAV_LOCATION}
      REALM: ${DOCUMENTATION_WEBDAV_REALM}
    volumes:
      - ./volumes/documentation-web/var_www_html/:/var/lib/dav/data/
      - ./configs/documentation-webdav/abes-dav.conf:/usr/local/apache2/conf/conf-available/dav.conf
      - ./configs/documentation-webdav/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
  documentation-sftp:
    build: ./images/documentation-sftp/
    mem_limit: ${DOCUMENTATION_SFTP_MEM_LIMIT:-5g}
    cpus: ${DOCUMENTATION_SFTP_CPU_LIMIT:-5}
    hostname: documentation-sftp
    container_name: documentation-sftp
    restart: unless-stopped
    ports:
      - "2222:22"
    environment:
      USER_NAME: ${DOCUMENTATION_SFTP_USERNAME}
      USER_PASS: ${DOCUMENTATION_SFTP_PASSWORD}
      SFTP_UID : ${DOCUMENTATION_SFTP_UID}
      SFTP_GID : ${DOCUMENTATION_SFTP_GID}
    volumes:
      - ./volumes/documentation-web/var_www_html/:/home/${DOCUMENTATION_SFTP_USERNAME}/sftp/html/
  documentation-rp:
    hostname: documentation-rp
    container_name: documentation-rp
    restart: unless-stopped
    image: nginx:1.26.1
    ports:
      - 38089:80
    volumes:
      - ./configs/documentation-rp/default-${DOCUMENTATION_ENV:-dev}.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - documentation-web
      - documentation-gm-swish-e
      - documentation-webdav
