version: "3.2"
services:
  documentation-web:
    build: .
    hostname: documentation-web
    container_name: documentation-web
    restart: unless-stopped
    ports:
      - 38080:80
    volumes:
      - ./volumes/documentation-web:/usr/local/apache2/htdocs/
      - ./volumes/documentation-web/conf/abes/:/usr/local/apache2/conf/abes/
  documentation-gm-swish-e:
    image: abesesr/swish-e-docker:1.1.1
    hostname: documentation-gm-swish-e
    container_name: documentation-gm-swish-e
    restart: unless-stopped
    ports:
      - 38081:80
    volumes:
      - ./volumes/documentation-gm-swish-e/html/:/var/ww/html/
      - ./volumes/documentation-gm-swish-e/data-swish-e/swish.cgi:/usr/lib/cgi-bin/swish.cgi
      - ./volumes/documentation-gm-swish-e/data-swish-e/TemplateDefault.pm:/usr/lib/swish-e/perl/SWISH/TemplateDefault.pm
      - ./volumes/documentation-gm-swish-e/data-swish-e/.swishcgi.conf:/usr/lib/cgi-bin/.swishcgi.conf
      - ./volumes/documentation-gm-swish-e/data-swish-e/:/opt/guide/data-swish-e/
