version: "3.2"
services:
  documentation-httpd:
    build: .
    hostname: documentation-httpd
    container_name: documentation-httpd
    restart: unless-stopped
    ports:
      - 38080:80
    volumes:
      - ./volumes/documentation-httpd:/usr/local/apache2/htdocs/
      - ./volumes/documentation-httpd/conf/:/usr/local/apache2/conf/abes/
  documentation-swich-e:
    build: ./swich-e/.
    hostname: documentation-swich-e
    container_name: documentation-swich-e
    restart: unless-stopped
    volumes:
      - ./volumes/documentation-swich-e:/opt/guide/data-swish-e/
    ports:
      - 38081:81
